// ملف الترجمات - جميع النصوص العربية في مكان واحد
// يمكن توسيعه لاحقاً ليدعم لغات متعددة

export const LABELS = {
  // ===== COMMON / SHARED =====
  common: {
    appName: 'متابعة السائق',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    success: 'تم بنجاح',
    confirm: 'تأكيد',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    submit: 'إرسال',
    yes: 'نعم',
    no: 'لا',
    all: 'الكل',
    active: 'نشط',
    inactive: 'غير نشط',
    status: 'الحالة',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    password: 'كلمة المرور',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    welcome: 'مرحباً',
    currency: 'ج.م',
    noResults: 'لا توجد نتائج',
    actions: 'الإجراءات',
    details: 'التفاصيل',
    filter: 'فلترة',
    sort: 'ترتيب',
    date: 'التاريخ',
    amount: 'المبلغ',
    total: 'الإجمالي',
    count: 'العدد',
    item: 'عنصر',
    order: 'الترتيب',
    color: 'اللون',
    commission: 'العمولة',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'تاريخ التحديث',
    selected: 'مختار',
    optional: 'اختياري',
    notes: 'ملاحظات',
    addNote: 'أضف ملاحظة',
    new: 'جديد',
    type: 'النوع',
    company: 'الشركة',
    allCompanies: 'جميع الشركات',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    clearFilters: 'مسح الفلاتر',
    highest: 'الأعلى',
    ofTotal: 'من الإجمالي',
    income: 'الدخل',
    expenses: 'المصروفات',
    profit: 'الربح',
    results: 'نتيجة',
    enabled: 'مفعل',
    disabled: 'معطل',
    operations: 'عملية',
    
    // Categories
    fuel: 'بنزين',
    maintenance: 'صيانة',
    mobile: 'موبايل',
    cleaning: 'تنظيف',
    other: 'أخرى',
    
    // Auth related
    welcomeBack: 'مرحباً بك مجدداً',
    loginSubtitle: 'سجل الدخول لمتابعة أرباحك ومصروفاتك',
    fillAllFields: 'يرجى ملء جميع الحقول',
    change: 'تغيير',
    passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    passwordMismatch: 'كلمة المرور غير متطابقة',
    registerSubtitle: 'ابدأ بتتبع دخلك من منصات النقل اليوم',
    confirmPassword: 'تأكيد كلمة المرور',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    
    // Add page
    chooseType: 'اختر نوع العملية التي تريد تسجيلها',
    choosePlatform: 'اختر المنصة',
    andMore: 'وغيرها',
    
    // Vehicle & Maintenance
    vehicleProfile: 'ملف السيارة',
    noVehicleYet: 'لم تضف سيارة بعد',
    addVehicleDesc: 'أضف سيارتك لتتبع الصيانة والمصروفات',
    brand: 'الماركة',
    model: 'الموديل',
    year: 'سنة الصنع',
    plateNumber: 'رقم اللوحة',
    maintenanceSchedule: 'جدول الصيانة',
    noMaintenanceItemsYet: 'لا توجد عناصر صيانة بعد',
    remaining: 'متبقي',
    lastChange: 'آخر تغيير',
    notRecorded: 'لم يتم التسجيل بعد',
    addMaintenanceItem: 'إضافة عنصر صيانة',
    remainingPct: 'النسبة المتبقية %',
    statusGood: 'حالة جيدة',
    statusWarning: 'يستحق قريباً',
    statusUrgent: 'عاجل',
    odometer: 'عداد المسافة',
    consumptionLabel: 'الاستهلاك',
    maintenanceLabel: 'الصيانة',
    activeLabel: 'نشطة',
    owner: 'المالك',
    distanceUnit: 'كم',
    consumptionUnit: 'لتر/100كم',

    // Goals & Achievements
    streak: 'سلسلة',
    days: 'يوم',
    thisMonth: 'هذا الشهر',
    bestDriver: 'أفضل سائق',
    goalAchiever: 'محقق الأهداف',
    achievedGoals: 'أهداف محققة',
    
    // Notifications
    noNotifications: 'لا توجد إشعارات',
    noNewNotifications: 'لا توجد إشعارات جديدة',
    unreadNotifications: 'إشعار غير مقروء',
    readAll: 'قراءة الكل',
    
    // Fuel Calculator
    fuelPrice: 'سعر اللتر (ج.م)',
    calculate: 'احسب',
    distance: 'المسافة (كم)',
    exampleDistance: 'مثال: 150',
    consumption: 'معدل الاستهلاك (لتر/100كم)',
    avgConsumption: 'المتوسط: 7-10 لتر/100كم للسيارات العادية',
  },

  // ===== NAVIGATION / TABS =====
  nav: {
    dashboard: 'الرئيسية',
    reports: 'التقارير',
    users: 'المستخدمين',
    vehicles: 'السيارات',
    companies: 'الشركات',
    support: 'الدعم',
    tickets: 'تذاكر الدعم',
    activity: 'السجل',
    notifications: 'الإشعارات',
    ads: 'الإعلانات',
    settings: 'الإعدادات',
    errorLogs: 'سجلات الأخطاء',
    backup: 'النسخ الاحتياطي',
    home: 'الرئيسية',
    profile: 'حسابي',
    goals: 'الأهداف',
    transactions: 'المعاملات',
    help: 'المساعدة',
    add: 'إضافة',
    forecast: 'التوقعات',
    achievements: 'الإنجازات',
    fuelNav: 'حاسبة الوقود',
  },

  // ===== ADMIN DASHBOARD =====
  admin: {
    title: 'لوحة التحكم',
    role: 'أدمن',
    exportCSV: 'تصدير CSV',
    
    // Stats
    totalUsers: 'المستخدمين',
    totalIncome: 'الدخل',
    totalExpenses: 'المصروفات',
    netProfit: 'صافي الربح',
    admins: 'أدمن',
    subscribers: 'مشترك',
    suspended: 'موقوف',
    
    // Top performers
    mostActive: 'أكثر نشاطاً',
    highestIncome: 'أعلى دخل',
    avgIncomePerUser: 'متوسط الدخل/مستخدم',
    
    // Today summary
    todaySummary: 'ملخص اليوم',
    todayIncome: 'دخل اليوم',
    todayExpenses: 'مصروفات اليوم',
    todayNet: 'صافي اليوم',
    
    // New features stats
    vehiclesCount: 'السيارات',
    maintenanceItems: 'عناصر الصيانة',
    alertSettings: 'إعدادات التنبيهات',
    notificationSettings: 'إعدادات الإشعارات',
    
    // Quick actions
    quickReports: 'التقارير',
    quickUsers: 'المستخدمين',
    quickVehicles: 'السيارات',
    quickActivity: 'السجل',
    quickNotifications: 'إشعارات',

    // Admin Controls & Labels
    sendNotification: 'إرسال إشعار',
    sendTo: 'إرسال إلى',
    allUsers: 'جميع المستخدمين',
    notificationTitle: 'عنوان الإشعار',
    notificationMessage: 'نص الإشعار...',
    noAds: 'لا توجد إعلانات بعد',
    addAdsDesc: 'أضف إعلانات بنر لعرضها للمستخدمين في الصفحة الرئيسية',
    saveChanges: 'حفظ التغييرات',
    createAd: 'إنشاء إعلان',
    promote: 'ترقية لأدمن',
    demote: 'تخفيض لمشترك',
    activate: 'تفعيل',
    suspend: 'إيقاف',
  },

  // ===== REPORTS =====
  reports: {
    monthlyChart: 'الدخل والمصروفات الشهرية',
    byCompany: 'الدخل حسب الشركة',
    byCategory: 'المصروفات حسب الفئة',
    bestWeekdays: 'أفضل أيام الأسبوع',
    userPerformance: 'أداء المستخدمين',
    monthComparison: 'مقارنة الأشهر',
    current: 'الحالي',
    fromLastMonth: 'عن الشهر السابق',
    monthlyBreakdown: 'تفاصيل الخصم الشهري',
    companyComparison: 'مقارنة الشركات',
    incomePerCompany: 'دخل كل شركة',
    monthlyIncome: 'الدخل الشهري',
    expensesByType: 'المصروفات حسب النوع',
    expenseDetails: 'تفاصيل المصروفات',
    monthlyExpenses: 'المصروفات الشهرية',
  },

  // ===== USERS =====
  users: {
    title: 'المستخدمين',
    searchPlaceholder: 'بحث بالاسم أو البريد...',
    editUser: 'تعديل بيانات المستخدم',
    deleteConfirm: (name: string) => `حذف "${name}"؟ سيتم حذف جميع بياناته نهائياً.`,
    toggleRoleConfirm: (role: string) => `${role === 'ADMIN' ? 'ترقية لأدمن' : 'تخفيض لمشترك'}؟`,
    suspendConfirm: (active: boolean) => `${active ? 'تفعيل' : 'إيقاف'} هذا الحساب؟`,
    roleAdmin: 'أدمن',
    roleSubscriber: 'مشترك',
    suspendedLabel: 'موقوف',
    newPassword: 'كلمة مرور جديدة (اختياري)',
    passwordPlaceholder: 'اتركه فارغاً لعدم التغيير',
    phonePlaceholder: '01xxxxxxxxx',
  },

  // ===== COMPANIES =====
  companies: {
    title: 'إدارة الشركات',
    add: 'إضافة شركة',
    edit: 'تعديل شركة',
    nameEn: 'اسم الشركة (إنجليزي)',
    nameAr: 'اسم الشركة (عربي)',
    commissionPercent: 'العمولة (%)',
    deleteConfirm: 'حذف هذه الشركة؟',
    noCompanies: 'لا توجد شركات',
  },

  // ===== TICKETS =====
  tickets: {
    title: 'تذاكر الدعم',
    all: 'الكل',
    open: 'مفتوحة',
    inProgress: 'قيد التنفيذ',
    resolved: 'محلولة',
    closed: 'مغلقة',
    urgent: 'عاجل',
    high: 'مرتفع',
    medium: 'متوسط',
    low: 'منخفض',
    reply: 'الرد على التذكرة',
    replyPlaceholder: 'اكتب ردك هنا...',
    sendReply: 'إرسال الرد',
    resolve: 'حل التذكرة',
    deleteConfirm: 'حذف هذه التذكرة؟',
    noTickets: 'لا توجد تذاكر',
    responses: 'رد',
  },

  // ===== SETTINGS =====
  settings: {
    title: 'إعدادات النظام',
    noSettings: 'لا توجد إعدادات محفوظة',
    autoAddNote: 'سيتم إضافة الإعدادات تلقائياً عند الحاجة',
    saved: 'تم حفظ الإعدادات',
  },

  // ===== ERROR LOGS =====
  errorLogs: {
    title: 'سجلات الأخطاء',
    clearOld: (days: number) => `حذف أقدم من ${days} أيام`,
    noLogs: 'لا توجد سجلات أخطاء',
    refresh: 'تحديث',
  },

  // ===== BACKUP =====
  backup: {
    title: 'النسخ الاحتياطي',
    description: 'قم بتحميل نسخة احتياطية من بيانات التطبيق بصيغة CSV',
    download: 'تحميل النسخة الاحتياطية',
    includes: 'يتضمن: المستخدمين، الدخل، المصروفات، الأهداف، السيارات، والمزيد',
    confirm: 'تأكيد إنشاء نسخة احتياطية؟',
  },

  // ===== ADS =====
  ads: {
    title: 'الإعلانات',
    add: 'إضافة إعلان جديد',
    edit: 'تعديل الإعلان',
    bannerText: 'بنر + نص',
    bannerLink: 'بنر + رابط',
    bannerVideo: 'بنر + فيديو',
    adTitle: 'عنوان الإعلان',
    adTitlePlaceholder: 'مثال: عرض خاص على البنزين',
    imageUrl: 'رابط صورة البنر',
    imagePlaceholder: 'https://example.com/banner.jpg',
    text: 'نص الإعلان',
    textPlaceholder: 'اكتب نص الإعلان هنا...',
    linkUrl: 'رابط الإعلان',
    videoUrl: 'رابط الفيديو',
    videoPlaceholder: 'https://youtube.com/watch?v=...',
    active: 'نشط',
    paused: 'متوقف',
    statusActive: 'نشط',
    statusPaused: 'متوقف',
    deleteConfirm: (title: string) => `حذف إعلان "${title}"؟`,
    requiredTitle: 'العنوان وصورة البنر مطلوبان',
  },

  // ===== VEHICLES =====
  vehicles: {
    title: 'السيارات',
    deleteConfirm: 'حذف هذه السيارة وجميع بيانات صيانتها؟',
    addVehicle: 'إضافة سيارة',
    editVehicle: 'تعديل',
    saveVehicle: 'حفظ السيارة',
    addMaintenance: 'إضافة عنصر صيانة',
    saveMaintenance: 'إضافة',
    maintenanceItemCount: 'عنصر',
    nameEn: 'الاسم (إنجليزي)',
    nameAr: 'الاسم (عربي)',
    odometerKm: 'عداد المسافة (كم)',
    consumptionPer100Km: 'استهلاك (لتر/100كم)',
    yearManufacture: 'سنة الصنع',
    plateNumberLabel: 'رقم اللوحة',
    optionalPlaceholder: 'اختياري',
    remainingPercent: 'النسبة المتبقية %',
    brandPlaceholder: 'تويوتا',
    modelPlaceholder: 'كامري',
    maintenanceNameArPlaceholder: 'زيت المحرك',
  },

  // ===== NOTIFICATIONS =====
  notifications: {
    title: 'الإشعارات',
    sendToAll: 'إرسال للجميع',
    sendToUser: 'إرسال لمستخدم محدد',
    titleLabel: 'العنوان',
    message: 'الرسالة',
    sent: 'تم الإرسال',
    sentToCount: (count: number) => `تم الإرسال لـ ${count} مستخدم`,
  },

  // ===== ACTIVITY LOG =====
  activity: {
    title: 'السجل',
    filter: 'فلترة النشاط',
    search: 'بحث في السجل...',
    actions: {
      LOGIN: 'دخول',
      INCOME_ADD: 'إضافة دخل',
      INCOME_DELETE: 'حذف دخل',
      EXPENSE_ADD: 'إضافة مصروف',
      EXPENSE_DELETE: 'حذف مصروف',
      ROLE_CHANGE: 'تغيير صلاحية',
      USER_SUSPENDED: 'إيقاف مستخدم',
      USER_UNSUSPENDED: 'تفعيل مستخدم',
      VEHICLE_ADD: 'إضافة سيارة',
      VEHICLE_UPDATE: 'تحديث سيارة',
      VEHICLE_DELETE: 'حذف سيارة',
      MAINTENANCE_ADD: 'إضافة صيانة',
      MAINTENANCE_UPDATE: 'تحديث صيانة',
      MAINTENANCE_DELETE: 'حذف صيانة',
      MAINTENANCE_SCHEDULE: 'جدول الصيانة',
      ALERT_SETTING_UPDATE: 'تحديث تنبيه',
      NOTIFICATION_SETTING_UPDATE: 'تحديث إشعار',
    },
  },

  // ===== WORK SESSIONS =====
  workSessions: {
    title: 'ساعات العمل',
    saved: 'تم الحفظ!',
    activeNow: 'جلسة نشطة الآن',
    startedAt: 'بدأت',
    end: 'إنهاء',
    addManual: 'إضافة يدوي',
    startNow: 'بدء الآن',
    startNew: 'بدء جلسة جديدة',
    addManualSession: 'إضافة جلسة يدوية',
    startTime: 'وقت البداية',
    endTime: 'وقت النهاية',
    notesOptional: 'ملاحظات (اختياري)',
    todayTotalHours: 'إجمالي ساعات اليوم',
    sessions: 'الجلسات',
    noSessionsToday: 'لا توجد جلسات لهذا اليوم',
    deleteConfirm: 'حذف هذه الجلسة؟',
    hour: 'ساعة',
    minute: 'دقيقة',
    and: 'و',
  },

  // ===== TRANSACTIONS =====
  transactions: {
    deleteConfirm: 'هل أنت متأكد من حذف هذا السجل؟',
    noTransactions: 'لا توجد عمليات مسجلة',
    startAdding: 'ابدأ بإضافة دخل أو مصروف',
  },

  // ===== GOALS =====
  goals: {
    title: 'الأهداف المالية',
    savedSuccess: 'تم حفظ الهدف بنجاح!',
    monthGoal: 'هدف',
    achieved: 'المحقق',
    achievedDone: 'تم التحقيق!',
    target: 'الهدف',
    dailyTarget: 'الهدف اليومي',
    dailyTargetDesc: 'اكسب',
    dailyTargetSuffix: 'إضافية اليوم للبقاء على المسار',
    remainingDays: 'متبقي',
    achievements: 'الإنجازات',
    addOrEditGoal: 'إضافة / تعديل هدف',
    month: 'الشهر',
    targetAmountLabel: 'الهدف (ج.م)',
    targetAmountPlaceholder: 'مثال: 15000',
    saving: 'جاري الحفظ...',
    saveGoal: 'حفظ الهدف',
    allGoals: 'جميع الأهداف',
    noGoalsYet: 'لم تحدد أي أهداف بعد',
    goalAchieved: 'تم تحقيق الهدف!',
    streakDone: 'عملت 7 أيام متتالية!',
    topDrivers: 'أفضل 5% من السائقين!',
    goalAchieverDone: 'حققت هدفك 3 مرات!',
    deleteConfirm: 'حذف هذا الهدف؟',
  },

  // ===== FUEL =====
  fuel: {
    totalCost: 'التكلفة الإجمالية',
    fuelAmount: 'كمية البنزين',
    literUnit: 'لتر',
    costPerKm: 'تكلفة الكيلومتر',
    currencyPerKm: 'ج.م/كم',
    quickReference: 'مرجع سريع',
    fuel80: 'بنزين 80',
    fuel92: 'بنزين 92',
    fuel95: 'بنزين 95',
  },

  // ===== VEHICLES LIST =====
  vehiclesPage: {
    title: 'المركبات',
    manage: 'إدارة',
    activeVehicle: 'السيارة النشطة',
    vehicleAndMaintenanceProfile: 'ملف السيارة والصيانة',
    noVehicles: 'لا توجد مركبات',
    noVehiclesDesc: 'ابدأ بإضافة سيارتك من صفحة ملف السيارة',
    addOrManageVehicles: 'إضافة / إدارة السيارات',
    activeBadge: 'نشطة',
    meterShort: 'عداد',
    consumptionShort: 'استهلاك',
    deleteConfirm: 'حذف هذه السيارة وجميع بياناتها؟',
  },

  // ===== ACHIEVEMENTS =====
  achievements: {
    title: 'الإنجازات',
    badgesTitle: 'الإنجازات والشارات',
    completed: 'مكتملة',
    ironDriver: 'سائق حديدي',
    ironDriverDone: '100 يوم عمل مكتمل',
    nightOwl: 'بومة الليل',
    nightOwlDone: '50 يوم عمل مكتمل',
    maintenanceKing: 'ملك الصيانة',
    maintenanceDone: 'كل مصاريف السيارة مسجلة',
    maintenancePrompt: 'سجل مصاريفك',
    achievedGoalDone: 'حققت هدفك 3 مرات',
  },

  // ===== MONTHS =====
  months: [
    'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو',
    'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'
  ],

  // ===== TIME AGO =====
  timeAgo: {
    now: 'الآن',
    minutes: (n: number) => `${n} د`,
    hours: (n: number) => `${n} س`,
    days: (n: number) => `${n} يوم`,
  },
} as const;

// Type for autocomplete support
export type LabelsType = typeof LABELS;
